# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vigenere(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 802)
        self.txt_key = QtWidgets.QPlainTextEdit(Form)
        self.txt_key.setGeometry(QtCore.QRect(210, 320, 481, 51))
        self.txt_key.setObjectName("txt_key")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(Form)
        self.txt_plain_text.setGeometry(QtCore.QRect(210, 160, 481, 131))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 60, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(Form)
        self.txt_cipher_text.setGeometry(QtCore.QRect(210, 410, 481, 131))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 400, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 320, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_decrypt = QtWidgets.QPushButton(Form)
        self.btn_decrypt.setEnabled(True)
        self.btn_decrypt.setGeometry(QtCore.QRect(670, 630, 121, 61))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_encrypt = QtWidgets.QPushButton(Form)
        self.btn_encrypt.setEnabled(True)
        self.btn_encrypt.setGeometry(QtCore.QRect(200, 630, 121, 51))
        self.btn_encrypt.setObjectName("btn_encrypt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Plantext"))
        self.label_2.setText(_translate("Form", "Dang Minh Kha - 2280601353"))
        self.label.setText(_translate("Form", "VIGENERE CIPHER "))
        self.label_5.setText(_translate("Form", "Cipher text"))
        self.label_4.setText(_translate("Form", "Key"))
        self.btn_decrypt.setText(_translate("Form", "decrypt"))
        self.btn_encrypt.setText(_translate("Form", "encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Vigenere()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
